<a href="https://colab.research.google.com/github/Kuoz2/An-lisis_y_Predicci-n/blob/main/Copia_de_tienda_retail_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Observaciones iniciales:

---
<p style="font-size:14px;">No se observan valores nulos (NaN) a simple vista en esta muestra inicial. Los datos financieros tienen una estructura limpia que nos permitirá realizar operaciones de suma y promedios directamente.</p>
---

In [ ]:
df = pd.read_csv('data/retail_sales_dataset.csv')

In [ ]:
df.head(10)

,Transaction ID,Date,Customer ID,Gender,Age,Tienda,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
5,6,2023-04-25,CUST006,Female,45,Beauty,1,30,30
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
9,10,2023-10-07,CUST010,Female,52,Clothing,4,50,200

#Verificación del Final del Dataset: df.tail(5)

---
<p style="font-size:14px;">Se utilizó el método tail(5) para inspeccionar los últimos 5 registros del DataFrame. Esta práctica es vital para comprobar la consistencia de los datos hasta el final del archivo, verificar el volumen total de transacciones cargadas y asegurar que no existan filas corruptas, nulas o de "totales" que frecuentemente se filtran al importar archivos CSV o Excel.</p>
---

In [ ]:
df.tail(5)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

## Uso de la herramienta df.info()

---
<p style="font-size:14px;">El comando df.info() confirma que el dataset contiene exactamente 1000 registros y 9 columnas sin ningún dato nulo. Los tipos de datos están estructurados correctamente en 5 variables numéricas (int64) para cálculos y 4 variables de texto (str) para categorías e identificadores. Al no tener valores faltantes y ser muy ligero en memoria (70.4 KB), es un dataset totalmente limpio y listo para trabajar.</p>
---

In [ ]:
df.describe()

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

#Resultado de df.types

---
<p style="font-size:14px;">El comando df.dtypes detalla el formato de cada columna, confirmando 5 variables numéricas (int64) listas para cálculos matemáticos o financieros. Además, muestra 4 variables de texto (str) que servirán para filtros y agrupaciones categóricas. Como observación técnica para futuros análisis, la columna Date está como texto y podría requerir conversión a formato fecha (datetime).</p>
---

In [ ]:
df.dtypes

Transaction ID      int64
Date                  str
Customer ID           str
Gender                str
Age                 int64
Product Category      str
Quantity            int64
Price per Unit      int64
Total Amount        int64
dtype: object

#Uso de value_counts()

---
<p style="font-size:14px;">El comando value_counts() contabiliza el total de transacciones para cada categoría única en la columna. El resultado revela que Clothing (Ropa) es el departamento con más ventas (351 registros), seguido muy de cerca por Electronics (342) y Beauty (307). Esto indica que el volumen de ventas de la tienda está distribuido de manera bastante equilibrada y saludable entre sus tres áreas principales.</p>
---

In [ ]:
df['Product Category'].value_counts()

Product Category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

#Preparación y estandarización de datos para el filtrado.

---
<p style="font-size:14px;">Justificación de las transformaciones: El requerimiento del ejercicio exige interactuar con entidades específicas como "Tienda" y "Ventas". Sin embargo, nuestro dataset original proviene de una fuente estructurada en inglés.Para poder aplicar los filtros solicitados sin que el sistema arroje errores de inconsistencia, es estrictamente necesario realizar una etapa de preprocesamiento y limpieza. Tomamos la decisión de aplicar este bloque de código por tres motivos técnicos: 1. Aislamiento: Evitar la alteración destructiva del dataset original. 2. Alineación de requisitos: Adaptar la nomenclatura de las columnas a las reglas de negocio exigidas por la evaluación. 3. Auditoría de datos: Conocer exactamente qué valores únicos componen nuestra nueva columna antes de intentar filtrarlos a ciegas.</p>
---

In [ ]:
df2=df.copy()
df2.rename(columns={'Product Category': 'Tienda'}, inplace=True)
valores_unico = df2['Tienda'].unique()
print(f"Valores unicos de la Tienda son: {valores_unico}")

Valores unicos de la Tienda son: <StringArray>
['Beauty', 'Clothing', 'Electronics']
Length: 3, dtype: str

#Filtrado condicional y slicing

---
<p style="font-size:14px;">El requerimiento solicita aislar las transacciones donde las ventas superen un umbral monetario específico mayores a 50 y presentar únicamente la información relevante al producto y monto.</p>
---

In [ ]:
ventas_mayores_cinc= df[df['Total Amount']>50][['Product Category', 'Total Amount']]
ventas_mayores_cinc

    Product Category  Total Amount
0             Beauty           150
1           Clothing          1000
3           Clothing           500
4             Beauty           100
7        Electronics           100
..               ...           ...
993           Beauty          1000
996           Beauty            90
997           Beauty           100
998      Electronics           150
999      Electronics           120

[783 rows x 2 columns]

#Filtrado condicional con ajuste de escala

---
<p style="font-size:14px;">Justificación de la transformación matemática: El enunciado original solicita filtrar las transacciones cuyo Precio sea menor a 0.5. Sin embargo, durante la exploración previa de la base de datos, se detectó que la columna 'Price per Unit' maneja una escala de valores enteros mucho más alta.Si se aplicaba el filtro literal 0.5 el sistema habría devuelto un DATAFRAME VACÍO, ya que los datos reales no están formateados en decimales o porcentaje. Para resolver esta discrepancia de unidades entre la regla de negocio y la realidad de los datos, se aplicó un factor de escalamiento o normalización. Se multiplicó el umbral por 100 (0.5 * 100) ajustando el límite a 50. Esto permite cumplir con el espíritu analítico del ejercicio "Buscar los productos de menor costo" adaptándolo a la magnitud real del dataset.</p>
---

In [ ]:
precios_bajos = df[df['Price per Unit'] < 0.5 * 100][['Product Category','Price per Unit']]
precios_bajos

    Product Category  Price per Unit
2        Electronics              30
5             Beauty              30
6           Clothing              25
7        Electronics              25
11            Beauty              25
..               ...             ...
991      Electronics              30
994         Clothing              30
996           Beauty              30
997           Beauty              25
999      Electronics              30

[393 rows x 2 columns]

In [ ]:
query_result= df.query("`Product Category` == 'Beauty' and `Total Amount` > 30")
query_result

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
11,12,2023-10-30,CUST012,Male,35,Beauty,3,25,75
20,21,2023-01-14,CUST021,Female,50,Beauty,1,500,500
24,25,2023-12-26,CUST025,Female,64,Beauty,1,50,50
...,...,...,...,...,...,...,...,...,...
981,982,2023-12-19,CUST982,Female,46,Beauty,3,30,90
989,990,2023-05-25,CUST990,Female,58,Beauty,2,500,1000
993,994,2023-12-18,CUST994,Female,51,Beauty,2,500,1000
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100

#Uso del método query()

---
<p style="font-size:14px;">Justificación de la simulación: El enunciado exige explícitamente filtrar el dataframe buscando el valor exacto "Manzana" dentro de una columna llamada "Producto", y evaluar una columna llamada "Ventas". Dado que nuestro dataset original corresponde a una tienda con categorías en inglés y carece del registro "Manzanas", ejecutar el código directamente sobre los datos reales arrojaría un error de sintaxis o un dataframe vacío. Para demostrar el dominio del método query() y cumplir estrictamente con los parámetros de evaluación sin destruir la base de datos original, se diseñó una estrategia de simulación de datos. Se preparó un entorno temporal de pruebas donde se tradujeron los esquemas y se "disfrazó" una categoría existente para que el motor lógico de pandas tuviera información válida que procesar.</p>
---

In [ ]:
df_copia= df.copy()
df_copia = df_copia.rename(columns={'Product Category': 'Producto', 'Total Amount':'Ventas'})

df_copia['Producto'] = df_copia['Producto'].replace({'Beauty': 'Manzanas'})

query_result = df_copia.query("Producto == 'Manzanas' and Ventas > 30")
display(query_result)

,Transaction ID,Date,Customer ID,Gender,Age,Producto,Quantity,Price per Unit,Ventas
0,1,2023-11-24,CUST001,Male,34,Manzanas,3,50,150
4,5,2023-05-06,CUST005,Male,30,Manzanas,2,50,100
11,12,2023-10-30,CUST012,Male,35,Manzanas,3,25,75
20,21,2023-01-14,CUST021,Female,50,Manzanas,1,500,500
24,25,2023-12-26,CUST025,Female,64,Manzanas,1,50,50
...,...,...,...,...,...,...,...,...,...
981,982,2023-12-19,CUST982,Female,46,Manzanas,3,30,90
989,990,2023-05-25,CUST990,Female,58,Manzanas,2,500,1000
993,994,2023-12-18,CUST994,Female,51,Manzanas,2,500,1000
996,997,2023-11-17,CUST997,Male,52,Manzanas,3,30,90
997,998,2023-10-29,CUST998,Female,23,Manzanas,4,25,100

In [ ]:
df_sl = df.copy()
df_sl = df_sl.rename(columns={
    'Product Category': 'Producto',
    'Total Amount': 'Ventas',
    'Customer ID': 'Tienda'
})

#Extracción especifica de datos slicing con metodo loc[]

---


<p style="font-size:14px;">Justificación del modelo de datos:
El enunciado exige mostrar un cruce de información entre las columnas 'Producto' y 'Tienda'. Debido a que la base de datos original no contenía explícitamente una columna de tienda, fue necesario realizar una adaptación lógica en `df_sl`. En lugar de renombrar una variable al azar, se tomó la decisión técnica y comercial de asignar el campo 'Customer ID' como 'Tienda'. Esto otorga coherencia estructural al modelo, asumiendo que los identificadores secuenciales funcionan como códigos de sucursal o franquicias que adquieren los productos.</p>
---

In [ ]:
print("Columna Producto y Ventas")
selec_column = df_sl[['Producto', 'Ventas']]
selec_column

Columna Producto y Ventas

        Producto  Ventas
0         Beauty     150
1       Clothing    1000
2    Electronics      30
3       Clothing     500
4         Beauty     100
..           ...     ...
995     Clothing      50
996       Beauty      90
997       Beauty     100
998  Electronics     150
999  Electronics     120

[1000 rows x 2 columns]

In [ ]:
print("Seleccion de filas con loc[] elijiendo filas desde el 5 al 10")
corte_loc = df_sl.loc[5:10, ['Producto', 'Tienda']]
display(corte_loc)

Seleccion de filas con loc[] elijiendo filas desde el 5 al 10

       Producto   Tienda
5        Beauty  CUST006
6      Clothing  CUST007
7   Electronics  CUST008
8   Electronics  CUST009
9      Clothing  CUST010
10     Clothing  CUST011

In [ ]:
print("Mostrando un rango de muestra con iloc primeras 5 filas y 3 columnas")
corte_iloc = df_sl.iloc[0:5, 0:3]
corte_iloc

Mostrando un rango de muestra con iloc primeras 5 filas y 3 columnas

   Transaction ID        Date Customer ID
0               1  2023-11-24     CUST001
1               2  2023-02-27     CUST002
2               3  2023-01-13     CUST003
3               4  2023-05-21     CUST004
4               5  2023-05-06     CUST005